# Generated by Django 4.2 on 2025-07-21 18:03

import core.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=355)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, validators=[core.models.validate_cpf])),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('limite_maximo', models.DecimalField(decimal_places=2, default=10000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('12.00'))])),
                ('limite', models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('12.00'))], verbose_name='Limite por Empréstimo')),
                ('banimento', models.BooleanField(default=False)),
                ('motivo_banimento', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1024)])),
                ('data_banimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('parcelas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('12.00'))])),
                ('porcentagem', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('motivo', models.TextField(blank=True, default='Preciso do empréstimo para comprar uma coisa específica.', null=True, validators=[django.core.validators.MaxLengthValidator(1024)])),
                ('comprovante', models.BinaryField(blank=True, null=True)),
                ('tipo_comprovante', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('numero_parcela', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=2)),
                ('comprovante', models.BinaryField(blank=True, null=True)),
                ('tipo_comprovante', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('emprestimo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emprestimo')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('telegram', 'Telegram')], default='celular', max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.cliente')),
            ],
        ),
    ]
