# Generated by Django 5.2.5 on 2025-08-30 19:28

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parcela_valor_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True, validators=[core.models.validate_token])),
                ('plataforma', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord')], default='telegram', max_length=10)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255, unique=True)),
                ('plataforma', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord')], default='telegram', max_length=10)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord')], default='telegram', max_length=10)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatid')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bottoken')),
            ],
        ),
    ]
